+++
title = "elispのtry/catchについて"
author = ["karuta"]
publishDate = 2022-01-29T00:00:00+09:00
tags = ["elisp"]
draft = true
+++

elispでtry/catchの書き方を整理しておこう.  

<!--more-->  

面白いのがtryは存在しないことである  
`catch` フォームの中で 特定のエラーが `throw` されると異常終了しなくなる。  

```elisp
(progn
  (catch 'exit
    (message "hi")
    (sleep-for 2)
    (throw 'exit nil))
  (message "hi2"))
```

ここではエコーエリアにhiを表示して、その2秒後に `exit` というエラー出してる。  
catchでエラーを捉えることができる。
